<?xml version="1.0"?>
<robot name="linorobot2_2wd" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find linorobot2_description)/urdf/4wd_properties.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/mech/base.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/mech/wheel.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/controllers/skid_steer.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/sensors/laser_new.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/sensors/stereo_camera.urdf.xacro" />

  <xacro:base 
    length="${base_length}" 
    width="${base_width}" 
    height="${base_height}" 
    mass="${base_mass}"
    wheel_radius="${wheel_radius}"
    wheel_pos_z="${wheel_pos_z}"
/>

  <xacro:wheel 
    side="front_left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:wheel 
    side="front_right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${-wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:wheel 
    side="rear_left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${-wheel_pos_x}" 
    pos_y="${wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:wheel 
    side="rear_right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${-wheel_pos_x}" 
    pos_y="${-wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:laser
      name="front_laser" 
      pos_x="${laser_pos_x}"
      pos_y="${laser_pos_y}"
      pos_z="${laser_pos_z}"
      rpy_x="${laser_rpy_x}"
      rpy_y="${laser_rpy_y}"
      rpy_z="${laser_rpy_z*2}"
      update_rate="${laser_update_rate}"
      field_of_view="${laser_field_of_view}"
      range_min="${laser_range_min}"
      range_max="${laser_range_max}"
      samples="${laser_samples}"
      resolution="${laser_resolution}"
  />

  <xacro:laser
      name="back_laser" 
      pos_x="${-laser_pos_x}"
      pos_y="${-laser_pos_y}"
      pos_z="${laser_pos_z}"
      rpy_x="${laser_rpy_x}"
      rpy_y="${laser_rpy_y}"
      rpy_z="${laser_rpy_z}"
      update_rate="${laser_update_rate}"
      field_of_view="${laser_field_of_view}"
      range_min="${laser_range_min}"
      range_max="${laser_range_max}"
      samples="${laser_samples}"
      resolution="${laser_resolution}"
  />

  <xacro:stereo_camera
      name="front_stereo_camera" 
      pos_x="${stereo_camera_pos_x}"
      pos_y="${stereo_camera_pos_y}"
      pos_z="${stereo_camera_pos_z}"
      rpy_x="${stereo_camera_rpy_x}"
      rpy_y="${stereo_camera_rpy_y}"
      rpy_z="${stereo_camera_rpy_z}"
      baseline="${stereo_camera_baseline}"
      update_rate="${stereo_camera_update_rate}"
      width="${stereo_camera_width}"
      height="${stereo_camera_height}"
      fov="${stereo_camera_fov}"
      near="${stereo_camera_near}"
      far="${stereo_camera_far}"
      side="front"
  />

  <xacro:stereo_camera
      name="back_stereo_camera" 
      pos_x="${-stereo_camera_pos_x}"
      pos_y="${stereo_camera_pos_y}"
      pos_z="${stereo_camera_pos_z}"
      rpy_x="${stereo_camera_rpy_x}"
      rpy_y="${stereo_camera_rpy_y}"
      rpy_z="${stereo_camera_rpy_z}"
      baseline="${stereo_camera_baseline}"
      update_rate="${stereo_camera_update_rate}"
      width="${stereo_camera_width}"
      height="${stereo_camera_height}"
      fov="${stereo_camera_fov}"
      near="${stereo_camera_near}"
      far="${stereo_camera_far}"
      side="back"
  />

  <xacro:diff_drive_controller
    wheel_separation="${wheel_pos_y * 2}"
    wheel_radius="${wheel_radius}"
    wheel_torque="${wheel_torque}"
  />
</robot>